esphome:
  name: helios-kwl

esp32:
  board: wemos_d1_mini32

# Enable logging
logger:
  level: DEBUG
  #baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret key

ota:
  platform: esphome
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".local"
  power_save_mode: none

status_led:
  pin: GPIO2

external_components:
  - source: components

uart:
  id: uart_bus
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600
  #debug:
    #dummy_receiver: true

helios_kwl:
  id: helios_kwl_0

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 30s

  - platform: helios_kwl
    helios_kwl_id: helios_kwl_0
    fan_speed:
      name: "Fan speed"
      id: fan_speed
    temperature_outside:
      name: "Temperature outside"
      id: sensor_temperature_outside
      filters:
        - median:
            window_size: 3
            send_every: 1
    temperature_exhaust:
      name: "Temperature exhaust"
      id: sensor_temperature_exhaust
      filters:
        - median:
            window_size: 3
            send_every: 1
    temperature_inside:
      name: "Temperature inside"
      id: sensor_temperature_inside
      filters:
        - median:
            window_size: 3
            send_every: 1
    temperature_incoming:
      name: "Temperature incoming"
      id: sensor_temperature_incoming
      filters:
        - median:
            window_size: 3
            send_every: 1

binary_sensor:
  - platform: helios_kwl
    helios_kwl_id: helios_kwl_0
    power_state:
      name: "Power state"
      id: power_state
    bypass_state:
      name: "By-pass state"
      id: bypass_state
    heating_indicator:
      name: "Heating indicator"
      id: heating_indicator
    fault_indicator:
      name: "Fault indicator"
      id: fault_indicator
    service_reminder:
      name: "Service reminder"
      id: service_reminder

switch:
  - platform: helios_kwl
    helios_kwl_id: helios_kwl_0
    winter_mode:
      name: "Winter mode"
      id: helios_kwl_winter

fan:
  - platform: speed
    output: helios_kwl_speed
    speed_count: 8
    name: "Fan speed"

output:
  - platform: helios_kwl
    helios_kwl_id: helios_kwl_0
    fan_speed:
      id: helios_kwl_speed
